/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuhu_galileocv_MotionDetector */

#ifndef _Included_com_fuhu_galileocv_MotionDetector
#define _Included_com_fuhu_galileocv_MotionDetector
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT JNICALL void Java_com_fuhu_galileocv_MotionDetector_findFeatures(JNIEnv*, jobject, jlong addrGray, jlong addrRgba);

JNIEXPORT JNICALL void Java_com_fuhu_galileocv_MotionDetector_detect(JNIEnv*, jobject, jlong addrRgba, jlong addrMotion);

JNIEXPORT JNICALL void Java_com_fuhu_galileocv_MotionDetector_objectTracking(
        JNIEnv* jenv, jobject, jlong addrRgba, jlong addrMotion, jstring typeString, jint index);

#ifdef __cplusplus
}
#endif
#endif
